/*
Copyright 2023 The Radius Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package output

import (
	"fmt"
	"strings"

	"github.com/radius-project/radius/pkg/corerp/api/v20231001preview"
)

// DiffMarkdownRenderer renders graph diffs as Markdown for GitHub PR comments.
type DiffMarkdownRenderer struct {
	// GitHubBaseURL is the base URL for linking to GitHub
	GitHubBaseURL string

	// IncludeMermaid enables Mermaid diagram generation
	IncludeMermaid bool

	// MaxChangesPerSection limits the number of changes shown per section
	MaxChangesPerSection int
}

// NewDiffMarkdownRenderer creates a new renderer with default settings.
func NewDiffMarkdownRenderer() *DiffMarkdownRenderer {
	return &DiffMarkdownRenderer{
		IncludeMermaid:       true,
		MaxChangesPerSection: 20,
	}
}

// RenderPRComment generates the full PR comment body from a graph diff.
func (r *DiffMarkdownRenderer) RenderPRComment(diff *v20231001preview.GraphDiff, before, after *v20231001preview.StaticAppGraph) string {
	var sb strings.Builder

	// Header
	sb.WriteString("## 📊 Application Graph Changes\n\n")

	// Quick summary badge
	summary := diff.Summary
	if summary.TotalChanges == 0 {
		sb.WriteString("✅ **No changes detected**\n\n")
		return sb.String()
	}

	sb.WriteString(r.renderSummaryBadges(summary))
	sb.WriteString("\n")

	// Collapsible details
	if len(diff.AddedResources) > 0 || len(diff.RemovedResources) > 0 || len(diff.ModifiedResources) > 0 {
		sb.WriteString("<details>\n<summary>View Details</summary>\n\n")

		// Before/After diagrams side by side
		if r.IncludeMermaid {
			sb.WriteString(r.renderBeforeAfterDiagrams(before, after))
		}

		// Change tables
		if len(diff.AddedResources) > 0 {
			sb.WriteString(r.renderAddedSection(diff.AddedResources))
		}

		if len(diff.RemovedResources) > 0 {
			sb.WriteString(r.renderRemovedSection(diff.RemovedResources))
		}

		if len(diff.ModifiedResources) > 0 {
			sb.WriteString(r.renderModifiedSection(diff.ModifiedResources))
		}

		sb.WriteString("</details>\n")
	}

	// Footer with metadata
	sb.WriteString("\n---\n")
	sb.WriteString("*Generated by Radius App Graph Action*\n")

	return sb.String()
}

// renderSummaryBadges creates the summary badges line.
func (r *DiffMarkdownRenderer) renderSummaryBadges(summary v20231001preview.DiffSummary) string {
	var badges []string

	if summary.ResourcesAdded > 0 {
		badges = append(badges, fmt.Sprintf("➕ %d added", summary.ResourcesAdded))
	}
	if summary.ResourcesRemoved > 0 {
		badges = append(badges, fmt.Sprintf("➖ %d removed", summary.ResourcesRemoved))
	}
	if summary.ResourcesModified > 0 {
		badges = append(badges, fmt.Sprintf("🔄 %d modified", summary.ResourcesModified))
	}
	if summary.ConnectionsAdded > 0 {
		badges = append(badges, fmt.Sprintf("🔗 +%d connections", summary.ConnectionsAdded))
	}
	if summary.ConnectionsRemoved > 0 {
		badges = append(badges, fmt.Sprintf("🔗 -%d connections", summary.ConnectionsRemoved))
	}

	return strings.Join(badges, " | ") + "\n"
}

// renderBeforeAfterDiagrams creates side-by-side before/after Mermaid diagrams.
func (r *DiffMarkdownRenderer) renderBeforeAfterDiagrams(before, after *v20231001preview.StaticAppGraph) string {
	var sb strings.Builder
	mermaid := NewMermaidGenerator()

	sb.WriteString("### Graph Visualization\n\n")

	// Use a table for side-by-side comparison in GitHub
	sb.WriteString("<table>\n<tr>\n")

	// Before column
	sb.WriteString("<td valign=\"top\">\n\n**Before**\n\n")
	if before != nil && len(before.Resources) > 0 {
		sb.WriteString(WrapInCodeBlock(mermaid.GenerateStaticGraph(before)))
	} else {
		sb.WriteString("*No previous graph*\n")
	}
	sb.WriteString("\n</td>\n")

	// After column
	sb.WriteString("<td valign=\"top\">\n\n**After**\n\n")
	if after != nil && len(after.Resources) > 0 {
		sb.WriteString(WrapInCodeBlock(mermaid.GenerateStaticGraph(after)))
	} else {
		sb.WriteString("*No current graph*\n")
	}
	sb.WriteString("\n</td>\n")

	sb.WriteString("</tr>\n</table>\n\n")

	return sb.String()
}

// renderAddedSection creates the added resources section.
func (r *DiffMarkdownRenderer) renderAddedSection(added []v20231001preview.StaticAppGraphResource) string {
	var sb strings.Builder

	sb.WriteString("### ➕ Added Resources\n\n")
	sb.WriteString("| Resource | Type |\n")
	sb.WriteString("|----------|------|\n")

	count := 0
	for _, d := range added {
		if count >= r.MaxChangesPerSection {
			sb.WriteString(fmt.Sprintf("| ... | *and %d more* |\n", len(added)-r.MaxChangesPerSection))
			break
		}
		name := d.Name
		if name == "" {
			name = extractResourceName(d.ID)
		}
		shortType := getShortResourceType(d.Type)
		sb.WriteString(fmt.Sprintf("| `%s` | %s |\n", escapeMarkdownTableCell(name), shortType))
		count++
	}

	sb.WriteString("\n")
	return sb.String()
}

// renderRemovedSection creates the removed resources section.
func (r *DiffMarkdownRenderer) renderRemovedSection(removed []v20231001preview.StaticAppGraphResource) string {
	var sb strings.Builder

	sb.WriteString("### ➖ Removed Resources\n\n")
	sb.WriteString("| Resource | Type |\n")
	sb.WriteString("|----------|------|\n")

	count := 0
	for _, d := range removed {
		if count >= r.MaxChangesPerSection {
			sb.WriteString(fmt.Sprintf("| ... | *and %d more* |\n", len(removed)-r.MaxChangesPerSection))
			break
		}
		name := d.Name
		if name == "" {
			name = extractResourceName(d.ID)
		}
		shortType := getShortResourceType(d.Type)
		sb.WriteString(fmt.Sprintf("| ~~`%s`~~ | %s |\n", escapeMarkdownTableCell(name), shortType))
		count++
	}

	sb.WriteString("\n")
	return sb.String()
}

// renderModifiedSection creates the modified resources section.
func (r *DiffMarkdownRenderer) renderModifiedSection(modified []v20231001preview.ResourceDiff) string {
	var sb strings.Builder

	sb.WriteString("### 🔄 Modified Resources\n\n")

	count := 0
	for _, d := range modified {
		if count >= r.MaxChangesPerSection {
			sb.WriteString(fmt.Sprintf("*...and %d more modified resources*\n\n", len(modified)-r.MaxChangesPerSection))
			break
		}

		name := d.Name
		if name == "" {
			name = extractResourceName(d.ID)
		}
		sb.WriteString(fmt.Sprintf("**%s**\n\n", escapeMarkdownTableCell(name)))

		if len(d.ChangedProperties) > 0 {
			sb.WriteString("| Property | Change |\n")
			sb.WriteString("|----------|--------|\n")

			for _, change := range d.ChangedProperties {
				oldVal := formatPropertyValue(change.OldValue)
				newVal := formatPropertyValue(change.NewValue)
				sb.WriteString(fmt.Sprintf("| `%s` | %s → %s |\n", escapeMarkdownTableCell(change.Path), oldVal, newVal))
			}
			sb.WriteString("\n")
		}

		count++
	}

	return sb.String()
}

// RenderStalenessWarning generates a warning message when the committed graph is stale.
func (r *DiffMarkdownRenderer) RenderStalenessWarning(committedHash, regeneratedHash string) string {
	return fmt.Sprintf(`⚠️ **Stale Graph Warning**

The committed app-graph.json appears to be out of sync with the source Bicep files.

| | Hash |
|--|------|
| Committed | %s |
| Expected | %s |

Please regenerate the graph by running:
`+"```bash\nrad app graph app.bicep\n```"+`

`, truncateHash(committedHash), truncateHash(regeneratedHash))
}

// RenderNoChangesComment generates the comment for PRs with no graph changes.
func (r *DiffMarkdownRenderer) RenderNoChangesComment() string {
	return `## 📊 Application Graph

✅ **No changes to application graph**

The application topology remains unchanged in this PR.

---
*Generated by Radius App Graph Action*
`
}
