#!/bin/bash

# ============================================================================
# Render graph diff as Markdown for PR comments
# Generates formatted Markdown with optional Mermaid diagrams
# ============================================================================

set -euo pipefail

# Check jq availability
if ! command -v jq &> /dev/null; then
    echo "Error: jq is required but not installed" >&2
    exit 1
fi

# Required environment variables
: "${DIFF_JSON:?DIFF_JSON environment variable is required}"

# Optional variables with defaults
INCLUDE_MERMAID="${INCLUDE_MERMAID:-true}"

# Render summary badges
render_badges() {
    local diff="$1"
    local badges=""
    
    local added
    local removed
    local modified
    added=$(echo "${diff}" | jq -r '.summary.resourcesAdded // 0')
    removed=$(echo "${diff}" | jq -r '.summary.resourcesRemoved // 0')
    modified=$(echo "${diff}" | jq -r '.summary.resourcesModified // 0')
    
    [[ "${added}" -gt 0 ]] && badges="${badges}➕ ${added} added | "
    [[ "${removed}" -gt 0 ]] && badges="${badges}➖ ${removed} removed | "
    [[ "${modified}" -gt 0 ]] && badges="${badges}🔄 ${modified} modified | "
    
    # Remove trailing separator
    badges="${badges% | }"
    echo "${badges}"
}

# Render added resources section
render_added_section() {
    local diff="$1"
    local count
    count=$(echo "${diff}" | jq '.addedResources | length')
    
    [[ "${count}" -eq 0 ]] && return
    
    cat << 'EOF'
### ➕ Added Resources

| Resource | Type |
|----------|------|
EOF
    
    echo "${diff}" | jq -r '.addedResources[] | "| `\(.name // .id)` | \(.type // "unknown") |"'
    echo ""
}

# Render removed resources section
render_removed_section() {
    local diff="$1"
    local count
    count=$(echo "${diff}" | jq '.removedResources | length')
    
    [[ "${count}" -eq 0 ]] && return
    
    cat << 'EOF'
### ➖ Removed Resources

| Resource | Type |
|----------|------|
EOF
    
    echo "${diff}" | jq -r '.removedResources[] | "| ~~`\(.name // .id)`~~ | \(.type // "unknown") |"'
    echo ""
}

# Render modified resources section
render_modified_section() {
    local diff="$1"
    local count
    count=$(echo "${diff}" | jq '.modifiedResources | length')
    
    [[ "${count}" -eq 0 ]] && return
    
    echo "### 🔄 Modified Resources"
    echo ""
    
    while IFS= read -r resource; do
        local name
        name=$(echo "${resource}" | jq -r '.name // .id')
        echo "**${name}**"
        echo ""
        
        local changes_count
        changes_count=$(echo "${resource}" | jq '.changedProperties | length')
        if [[ "${changes_count}" -gt 0 ]]; then
            echo "| Property | Change |"
            echo "|----------|--------|"
            echo "${resource}" | jq -r '.changedProperties[] | "| `\(.path)` | \(.oldValue // "none") → \(.newValue // "none") |"'
            echo ""
        fi
    done < <(echo "${diff}" | jq -c '.modifiedResources[]')
}

# Render simple Mermaid diagram
render_mermaid() {
    local diff="$1"
    
    cat << 'EOF'
### Graph Visualization

```mermaid
graph LR
EOF
    
    # Render added resources with green styling
    echo "${diff}" | jq -r '.addedResources[] | "    \(.id | gsub("[^a-zA-Z0-9]"; "_"))[\"\(.name // .id)\"]:::added"'
    
    # Render removed resources with red styling
    echo "${diff}" | jq -r '.removedResources[] | "    \(.id | gsub("[^a-zA-Z0-9]"; "_"))[\"\(.name // .id)\"]:::removed"'
    
    # Render modified resources with yellow styling
    echo "${diff}" | jq -r '.modifiedResources[] | "    \(.id | gsub("[^a-zA-Z0-9]"; "_"))[\"\(.name // .id)\"]:::modified"'
    
    cat << 'EOF'
    
    classDef added fill:#90EE90,stroke:#228B22
    classDef removed fill:#FFB6C1,stroke:#DC143C
    classDef modified fill:#FFFACD,stroke:#DAA520
```

EOF
}

main() {
    local diff="${DIFF_JSON}"
    
    # Build comment body
    local body=""
    
    # Header
    body+="## 📊 Application Graph Changes"$'\n\n'
    
    # Summary badges
    local badges
    badges=$(render_badges "${diff}")
    [[ -n "${badges}" ]] && body+="${badges}"$'\n\n'
    
    # Collapsible details
    body+="<details>"$'\n'
    body+="<summary>View Details</summary>"$'\n\n'
    
    # Mermaid diagram
    if [[ "${INCLUDE_MERMAID}" == "true" ]]; then
        body+=$(render_mermaid "${diff}")
    fi
    
    # Change sections
    body+=$(render_added_section "${diff}")
    body+=$(render_removed_section "${diff}")
    body+=$(render_modified_section "${diff}")
    
    body+="</details>"$'\n\n'
    
    # Footer
    body+="---"$'\n'
    body+="*Generated by Radius App Graph Action*"$'\n'
    
    # Output for GitHub Actions using heredoc delimiter
    {
        echo "comment-body<<RENDER_EOF"
        echo "${body}"
        echo "RENDER_EOF"
    } >> "${GITHUB_OUTPUT:-/dev/stdout}"
    
    echo "Render complete"
}

main "$@"
